# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
services:
  grafana:
    # https://hub.docker.com/r/grafana/grafana/tags
    image: grafana/grafana:8.3.4
    container_name: csca5028-grafana
    ports:
      - "3000:3000"
    #networks:
     # - "rabbitmq-prometheus"
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./dashboards:/dashboards
    restart: always
    environment:
      # https://grafana.com/plugins/flant-statusmap-panel
      # https://grafana.com/plugins/grafana-piechart-panel
      # https://grafana.com/plugins/grafana-polystat-panel
      # https://grafana.com/plugins/jdbranham-diagram-panel
      # https://grafana.com/plugins/michaeldmoore-multistat-panel
      # https://grafana.com/plugins/vonage-status-panel
      # https://grafana.com/plugins/yesoreyeram-boomtable-panel
      GF_INSTALL_PLUGINS: "flant-statusmap-panel,grafana-piechart-panel,grafana-polystat-panel,jdbranham-diagram-panel,vonage-status-panel,yesoreyeram-boomtable-panel"  
  prometheus:
    # https://hub.docker.com/r/prom/prometheus/tags
    image: prom/prometheus
    container_name: csca5028-prometheus
    #networks:
     # - "rabbitmq-prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./http_pong.yml:/etc/prometheus/blackbox/http_pong.yml
    restart: always

  blackbox-exporter:
    # https://hub.docker.com/r/prom/blackbox-exporter/tags
    image: prom/blackbox-exporter:v0.19.0
    container_name: csca5028-blackbox-exporter
    #networks:
     # - "rabbitmq-prometheus"
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/config/blackbox.yml